### ISSUE TITLE
Include llama.cpp (ggml) in Nitro

### ISSUE THREAD

**Issue by tikikun** [janhq/nitro#10]
llama cpp is great and should be implemented into nitro core

**Comment by 0xSage** [comment]
please elaborate

**Comment by tikikun** [comment]
Outcome:
- In-process llama.cpp inside nitro core
Problem:
- Nitro does not currently have any in-process inference engine, which will make nitro unable to stand on its own feet when there is no external system (in this case triton) to connect to.

**Comment by tikikun** [comment]
Done with repo swap
