### ISSUE TITLE
feat: Add `pip` installation

### ISSUE THREAD

**Issue by hiro-v** [janhq/nitro#100]
**Problem**
- Currently the installation of Nitro is quite manual (I have to download binaries from release)
- No universal way to install

**Success Criteria**
- `pip install nitro`
- `nitro` as universal command (resides in `usr/local/bin` in Mac/ Linux or in windows)
- Automatically check for CPU arch and OS to install correct binary.
- CD for publishing to `pypi`

**Additional context**
None

**Comment by dan-jan** [comment]
@tikikun @linhtran174 @hiento09 Can I recommend we move this to one of the Nitro milestones, vs. "distribution"?

**Comment by hiento09** [comment]
I am going to close this, will reopen later
