### ISSUE TITLE
bug: infinite loop error with Nitro

### ISSUE THREAD

**Issue by louis-jan** [janhq/nitro#105]
**Describe the bug**
I got this error randomly, stuck in a loop, can't inference

**To Reproduce**
try load a tiny model (19MB)
https://huggingface.co/aladar/TinyLLama-v0-GGUF/resolve/main/TinyLLama-v0.f32.gguf

**Expected behavior**
Its loaded

**Screenshots**
<img width="489" alt="Screenshot 2023-11-06 at 10 51 46" src="https://github.com/janhq/nitro/assets/133622055/eb746ac9-56b6-40b6-bfd5-9f04801ce791">

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by tikikun** [comment]
is this specifically with that small model, do you experience with most models

**Comment by louis-jan** [comment]
I only see this one. Let's just close for now @tikikun since nitro is updated, will observe and let you know.
