### ISSUE TITLE
feat: Nitro support for linux (with/ without CUDA) with ARM64 support

### ISSUE THREAD

**Issue by vuonghoainam** [janhq/nitro#110]
**Problem**
- I tested nitro build on AWS Graviton3 which yields better result even compared to my personal computer
- Tried it with my Lambda which scales infinitely which is good

**Success Criteria**
- Nitro executables for Linux ARM64 that I can load model and call API

**Additional context**
None

**Comment by hiento09** [comment]
@vuonghoainam can you put your test results here (would be better with screenshot) and list dependencies, steps to build on Graviton3 / ARM64 so that we can add the arm64 CI agent later

**Comment by dan-jan** [comment]
@vuonghoainam @hiento09 I'm going to close this ticket first based on nitro-linux-arm64 being abailable. Please let me know if I closed it incorrectly and we can reopen.
