### ISSUE TITLE
feat: Healthcheck endpoint for model loaded and able to do inference

### ISSUE THREAD

**Issue by vuonghoainam** [janhq/nitro#119]
**Problem**
- When integrating Nitro, it's hard to know if model is able to do inference after `model_loaded` api. I can only tell there is a problem if it fails inference.

**Success Criteria**
- /api/health, return 200 if the model is loaded and ready to do inference. The app will poll this API. This should throw 500 to let app know that there is some problems that Nitro cannot fix itself and needs restarting.

**Additional context**
None

**Comment by louis-jan** [comment]
@vuonghoainam @tikikun /api/health is for nitro not model right? (I remember we added this kind of health check before) should we have current loaded model api so I can check what model (file name ...) is running (incase user don't have a state management system, app is reloaded somehow). I'm not sure if this does work - please cmiiw
