### ISSUE TITLE
feat: Nitro to support dumping logs locally

### ISSUE THREAD

**Issue by vuonghoainam** [janhq/nitro#120]
**Problem**
- When integrating Nitro as sub process, it's hard to track if there is any problem with it.
- Nitro needs "derisking" the release and able to reproduce bugs and fix sooner than later

**Success Criteria**
- Add a flag in build, or in load model to 1. enable dump logs to file | 2. logs file path - txt
- This file should includes input/ output so that it's easy to track problems. If user has problem, he/ she/ they can upload the file to the issue and Nitro contributors can reproduce and fix it.

**Additional context**
File content:
- OS
- Spec
- Input: Model name, model params
- Logs

**Comment by tikikun** [comment]
You should be able to get stddout at the moment through subprocess spawning? we only need this to debug on nitro level

**Comment by tikikun** [comment]
<img width="738" alt="image" src="https://github.com/janhq/nitro/assets/22268502/79f51436-c88c-415a-b002-ff0f1f155ab9">
https://stackoverflow.com/questions/36045588/reading-from-a-stdout-in-real-time-using-node-js

**Comment by tikikun** [comment]
I suggest we convert this issues into specifying what logs type to print to stddout, rather than an issue for writing stddout log to file, stddout to file can be resolved in many ways without any effort.
