### ISSUE TITLE
epic: intel hardware inferencing for nitro

### ISSUE THREAD

**Issue by tikikun** [janhq/nitro#140]
Using the below package from intel 

https://github.com/intel/intel-extension-for-transformers

![image](https://github.com/janhq/nitro/assets/22268502/f20abd3d-229a-4b8b-88ef-be4dab6d8637)

They claimed to outperform llama.cpp with their custom implementation. A potential candidate for integration.

**Comment by 0xSage** [comment]
dupe of #214
