### ISSUE TITLE
feat: improvements on nitro landing page

### ISSUE THREAD

**Issue by tikikun** [janhq/nitro#169]
## Nitro vs OpenAI

- Wrong api endpoint @urmauur 
![image](https://github.com/janhq/nitro/assets/101145494/2b0d3cf1-97f8-4a16-9153-eb437ddfa234)

## Remove Speed section
- Please remove the speed section since we will not do speed comparison

## Hero CTAs

- "Github" Button -> lead to the release page of nitro at https://github.com/janhq/nitro/releases
- Try to have a Github logo on the Github button (see SuperAGI's below)

![image](https://github.com/janhq/nitro/assets/101145494/e5a74bfe-7c81-42d3-b393-54f007744717)
![image](https://github.com/janhq/nitro/assets/101145494/f4a7606e-0b1c-4c6e-8c9a-5ffee92fc8b9)

## Engine Logos

- Please add logo to the engine 
<img width="965" alt="image" src="https://github.com/janhq/nitro/assets/22268502/4c531dc9-9150-4bd5-a03d-0b6a31e8abb5">

**Comment by dan-jan** [comment]
@tikikun @urmauur I have edited the Task Description to be more specific
