### ISSUE TITLE
feat: very fast install script

### ISSUE THREAD

**Issue by tikikun** [janhq/nitro#170]
**Problem**
Install must be even easier

**Success Criteria**
<img width="619" alt="image" src="https://github.com/janhq/nitro/assets/22268502/6ca16588-7d54-4f98-89e9-a323a04f6943">

**Comment by vuonghoainam** [comment]
solution:
- The feel of `bash -c "$(curl -s https://ggml.ai/server-llm.sh)"` with Mac/Linux/Windows
- Combine https://raw.githubusercontent.com/janhq/nitro/main/install.sh for downloading nitro and https://github.com/janhq/nitro/tree/main/.github/scripts for downloading model, loading model and yield command that it's ready to use

**Comment by dan-jan** [comment]
@vuonghoainam Wouldn't it be a very long process, especially if the model is huge?

**Comment by vuonghoainam** [comment]
Yes, it's of course a very long process but good for `Quick start`
We can decide on smaller model as quick start, and for `Slow usage` later, can use another bigger models
