### ISSUE TITLE
bug: nitro landing page looks off on search engine

### ISSUE THREAD

**Issue by tikikun** [janhq/nitro#190]
It seems not retaining the logo now

<img width="886" alt="image" src="https://github.com/janhq/nitro/assets/22268502/83a22680-6120-46e2-9f20-94a456e2ae88">

**Comment by urmauur** [comment]
@tikikun is someone fix this bugs? 

<img width="936" alt="Screenshot 2023-11-25 at 00 37 25" src="https://github.com/janhq/nitro/assets/10354610/15be2cae-a72f-42f5-8f8e-c13d505979e4">

<img width="779" alt="Screenshot 2023-11-25 at 00 38 21" src="https://github.com/janhq/nitro/assets/10354610/d50cc6b4-3485-4db3-b630-b3f88928f5e5">

i'm trying and got the logo, maybe google need time to indexing our pages, can you try again and let me know if you still have this issue @tikikun
