### ISSUE TITLE
epic: Nitro has a client library

### ISSUE THREAD

**Issue by 0xSage** [janhq/nitro#203]
**Problem**

**Success Criteria**

**Sub Issues**
- 

**Additional context**
Add any other context or screenshots about the epic request here.

**Comment by tikikun** [comment]
This is being done in #367

**Comment by tikikun** [comment]
@louis-jan is reviewing the PR

**Comment by imtuyethan** [comment]
Close as duplicated with https://github.com/janhq/jan/issues/1078
