### ISSUE TITLE
epic: queue system

### ISSUE THREAD

**Issue by 0xSage** [janhq/nitro#215]
## Objective

- Do we need a simple queue system?

### Motivation

_Nullpointer Errors?_
- Currently, inference requests are handled FIFO
- We are adopting an OpenAI API, which means that we will receive requests across Chat, Audio, Vision etc
- Given that users are on laptops with limited RAM and VRAM, we are likely to have to switch models

_Preparing for Cloud Native_
- Our long-term future is likely as an enterprise OpenAI-alternative, which will be multi-user and have a queue system
- Should we bake in this abstraction, and use a local file-based queue (which is later swapped out for a more sophisticated queue?)

**Comment by tikikun** [comment]
add simple queue

**Comment by tikikun** [comment]
https://github.com/janhq/nitro/issues/358

**Comment by tikikun** [comment]
for further
