### ISSUE TITLE
bug: Can not install in Windows

### ISSUE THREAD

**Issue by juanjgit** [janhq/nitro#234]
**Describe the bug**
The install.bat script fails on Windows 11

**To Reproduce**
1.  Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/janhq/nitro/main/install.bat' -OutFile 'install.bat'
2. .\install.bat
3. See error:

```txt
> 
Removing existing Nitro installation...
latest
Downloading Nitro from: https://github.com/janhq/nitro/releases/download/v0.1.20/nitro-0.1.20-win-amd64.tar.gz
Extracting Nitro...
Expand-Archive : .gz is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:1
+ Expand-Archive -Path 'C:\Users\JUAN~1.ACE\AppData\Local\Temp\nitro.ta ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (.gz:String) [Expand-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive
```

**Expected behavior**
Installer should run with no errors and successfully install or at least return an error message with the required minimum powershell version.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - PowerShell: 5.1

**Comment by mamadjadali** [comment]
> **Describe the bug**
> The install.bat script fails on Windows 11
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1.  Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/janhq/nitro/main/install.bat' -OutFile 'install.bat'
> 2. .\install.bat
> 3. See error:
> 
> ```txt
> > 
> Removing existing Nitro installation...
> latest
> Downloading Nitro from: https://github.com/janhq/nitro/releases/download/v0.1.20/nitro-0.1.20-win-amd64.tar.gz
> Extracting Nitro...
> Expand-Archive : .gz is not a supported archive file format. .zip is the only supported archive file format.
> At line:1 char:1
> + Expand-Archive -Path 'C:\Users\JUAN~1.ACE\AppData\Local\Temp\nitro.ta ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (.gz:String) [Expand-Archive], IOException
>     + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive
> ```
> 
> **Expected behavior**
> Installer should run with no errors and successfully install or at least return an error message with the required minimum powershell version.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
>  - OS: Windows 11
>  - PowerShell: 5.1
> 
>

**Comment by mamadjadali** [comment]
consider using PowerShell version 7 or later, as it might have better support for handling different archive formats.

**Comment by dlaliberte** [comment]
> consider using PowerShell version 7 or later, as it might have better support for handling different archive formats.

Or use the WSL 2 app.  You'll have to install jq as well.

**Comment by mamadjadali** [comment]
try installing the CUDA Toolkit 12 libraries alongside the CUDA Toolkit 11 ones,
sudo apt-get install libcudart.so.12.0
If this does not work, you can try finding the location of the libcudart.so.12 file using the command sudo find / -name 'libcudart.so.12' and then adding the path to the environment file.

**Comment by dlaliberte** [comment]
Got it working, thanks.  Next issue was, as I recall (it was many hours ago lol), the openai api support is not very complete for my needs.

**Comment by mitosagi** [comment]
Using tar.exe instead of Expand-Archive worked.
```powershell
powershell -Command "& { Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/janhq/nitro/main/install.bat' -OutFile 'install.bat'; (Get-Content .\install.bat) | %{ `$_ -replace 'Expand-Archive -Path','mkdir `"%APPDATA%\nitro`" | tar -zxvf' }  | %{ `$_ -replace 'DestinationPath','C' } | Set-Content .\install.bat; .\install.bat }"
```
