### ISSUE TITLE
bug: No static compilation or failed to find dll on windows

### ISSUE THREAD

**Issue by tikikun** [janhq/nitro#240]
**Describe the bug**
<img width="824" alt="image" src="https://github.com/janhq/nitro/assets/22268502/400bdade-cb6b-4e0a-bd18-e14bbbed6478">

**To Reproduce**
Windows on cuda

**Comment by linhtran174** [comment]
Linking this to: 
- [ ] https://github.com/janhq/nitro/issues/256

**Comment by hiento09** [comment]
only cudart64_12.dll and zlib.dll now is not able to add as static compilation. I will comback will another approach for cuda dependencies stuff later.
