### ISSUE TITLE
bug: Nitro Linux GPU tensor core issues, illegal instruction (core dumped)

### ISSUE THREAD

**Issue by hiento09** [janhq/nitro#273]
**Describe the bug**
I am able to use Nitro Linux GPU on GPUs that have tensor cores, such as the 3080ti. However, when I tested it on a GTX 1660ti, which does not have tensor cores, the Nitro process crashed with the log error illegal instruction (core dumped) (see picture below).

- OS: ubuntu 22.04
- nvidia driver version: 535
- cuda toolkit version: 12.3

**Screenshots**
![image](https://github.com/janhq/nitro/assets/136591877/cd93ed5f-a164-490b-9485-96411c30da06)
![image](https://github.com/janhq/nitro/assets/136591877/32b7d300-7cad-4015-9887-6e964fae8680)

**Comment by tikikun** [comment]
have a possible fix plz qa @hiento09

**Comment by hiento09** [comment]
PR to fix this bug https://github.com/janhq/nitro/pull/274

**Comment by lovehunter9** [comment]
I still got this bug.
<img width="1142" alt="image" src="https://github.com/janhq/nitro/assets/39935488/5739e99e-eca4-4614-9e1f-f6af2a52ba23">
