### ISSUE TITLE
feat: Colab for Nitro

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/nitro#281]
Link:

https://colab.research.google.com/drive/1mJKjPmPcsZKpRZsaO6Fn9G9aCBkjozrL?usp=sharing

**Comment by vuonghoainam** [comment]
I finished this with https://colab.research.google.com/drive/1mJKjPmPcsZKpRZsaO6Fn9G9aCBkjozrL?usp=sharing with the help from Stella and Alan
