### ISSUE TITLE
How can one set the parameters via CLI when starting a server?

### ISSUE THREAD

**Issue by syddharth** [janhq/nitro#319]
Is this already possible?

If not, could this be a feature? For example:
```
 .\nitro 4 127.0.0.1 5000 --ngl 20
```
on a Windows11 machine with NVIDIA GPU.

**Comment by tikikun** [comment]
hi friend you can have a look at the docs
https://nitro.jan.ai/docs

**Comment by tikikun** [comment]
https://nitro.jan.ai/features/load-unload

This section specifically, we don't support at runtime right now, mostly during the curl to load model
