### ISSUE TITLE
bug: ChatGPT-Next-Web does not work properly with nitro

### ISSUE THREAD

**Issue by caizongchao** [janhq/nitro#336]
Chat GPT Next (https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web.git) reports "fetch error" while connecting to nitro server. 

Recompile nitro with ALLOW_ALL_CORS resolved this issue, but it still cannot work properly in streaming mode. The content-type of nitroStreamResonse has to be set to "text/event-stream" to make response streaming work properly.

`
drogon::HttpResponse::newStreamResponse(callback, attachmentFileName, drogon::CT_CUSTOM, "text/event-stream");
`

**Comment by tikikun** [comment]
I have the same issue as you also, even tho it seems working fine on other UIs, very strange

**Comment by tikikun** [comment]
if you're familiar with chatgptnextweb, can support debugging on that end

**Comment by tikikun** [comment]
close due to non responding
