### ISSUE TITLE
feat: Support GBNF Grammars

### ISSUE THREAD

**Issue by LouisIV** [janhq/nitro#347]
**Problem**
Currently there is no support for GBNF grammars in the API. If there is its poorly documented.

**Success Criteria**
Llama.cpp supports GBNF grammars which is really useful when trying to emulate OpenAI function calling (this is actually the approach that LocalAI takes to do this). I would love to see that support exposed in some manner.

**Additional context**
n/a

**Comment by tikikun** [comment]
it's already support in https://github.com/janhq/nitro/pull/348
