### ISSUE TITLE
bug: Nitro LVM hang in 2nd request

### ISSUE THREAD

**Issue by hiro-v** [janhq/nitro#362]
**Describe the bug**
- `chat/completion` hangs at 2nd request with LLM

**To Reproduce**
1. Download llava gguf models
2. Load model
```
curl --location 'http://127.0.0.1:3928/inferences/llamacpp/loadmodel' \
--header 'Content-Type: application/json' \
--data '{
   "llama_model_path": "/Users/hiro/Downloads/ggml-model-q4_k.gguf",
   "mmproj": "/Users/hiro/Downloads/mmproj-model-f16.gguf",
   "ctx_len": 2048,
   "ngl": 100,
   "cont_batching": false,
   "embedding": false,
   "system_prompt": "",
   "user_prompt": "\n### Instruction:\n",
   "ai_prompt": "\n### Response:\n"
 }'
```
3. Call chat completion first time
```
curl --location 'http://127.0.0.1:3928/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
    "model": "gpt-4-vision-preview",
    "messages": [
      {
        "role": "user",
        "content": [
          {
            "type": "text",
            "text": "What’s in this image?"
          },
          {
            "type": "image_url",
            "image_url": {
              "url": "<base64>"
            }
          }
        ]
      }
    ],
    "max_tokens": 300
  }'
```
4. Repeat for second time, you will see it hangs

**Expected behavior**
- No hanging, same performance everytime

**Screenshots**
- Log ok for the first time
![CleanShot 2024-01-18 at 17 30 58](https://github.com/janhq/nitro/assets/22463238/25b236d7-9d52-4cbf-b10f-af1169d788ce)
- Log for 2nd time, hung up
![CleanShot 2024-01-18 at 17 31 25](https://github.com/janhq/nitro/assets/22463238/12197d9e-c5f6-4960-a2ba-d873160c9ec4)

**Desktop (please complete the following information):**
 - Mac Silicon

**Additional context**
- This happens both in https://github.com/janhq/nitro/commit/902dc3f6a7fa091e57f8b05623d7f9ab2d8280b7 and https://github.com/janhq/nitro/releases/tag/v0.2.11

**Comment by tikikun** [comment]
can you retry, should be fixed
