### ISSUE TITLE
bug: Website isn't up to date, install command doesn't work

### ISSUE THREAD

**Issue by MauroDruwel** [janhq/nitro#374]
# Website Issue: Discrepancy Between Homepage Command and `README.md`

**Describe the bug**
The command provided on the homepage does not work as expected. It appears to be out of sync with the current instructions in the `README.md` file. 
`powershell -Command "& { Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/janhq/nitro/main/install.bat' -OutFile 'install.bat'; .install.bat; Remove-Item -Path 'install.bat' }"`

**To Reproduce**
1. Go to the project homepage
2. Follow the installation command provided
3. Attempt to execute the command in the terminal

**Expected behavior**
The command provided on the homepage should match the current instructions in the `README.md` file and execute without errors.

**Screenshots**
![image](https://github.com/janhq/nitro/assets/46003176/bcd8ac60-df48-445f-a477-6f59879a4308)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 120.0.6099.225

**Additional context**
This issue was discovered during the process of installing the application via the website command.
I think a quick fix is just to sync/update the website, with the Github files.

**Comment by tikikun** [comment]
encourage everyone to just use the binary, the script is supposedly a helper and doesn't guarantee working
