### ISSUE TITLE
bug: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by KweezyCode** [janhq/nitro#393]
**Describe the bug**
I used guide from project description and got `Illegal instruction (core dumped)`

**Expected behavior**
working nitro

OS: Ubuntu 22.04.3 LTS x86_64
Kernel: 5.15.0-91-generic
CPU: Intel Pentium Silver J5040 (4) @ 3.200GHz

**Comment by hiento09** [comment]
Hi @KweezyCode ,  can you provide which version of Nitro that you use? Also, a log and screen capture would be great. Thank you.

**Comment by KweezyCode** [comment]
kweezy@j5040:~$ nitro --version
Illegal instruction (core dumped)

i think it is the latest from github, it is not working at all

**Comment by KweezyCode** [comment]
> @KweezyCode which `nitro` binary did you download and install? Could you share with us the `.tar.gz` file name? I believe that you downloaded the wrong tar file, that's why you see this error

i have built it from source, same error. I also tried amd64 tar file, same error. Btw, my processor doesn't support AVX, i don't know do you use it or no

**Comment by KweezyCode** [comment]
it works
