### ISSUE TITLE
Implement JSON_VALIDATOR for multi-part form data type

### ISSUE THREAD

**Issue by tikikun** [janhq/nitro#4]
Currently only support JSON form, so if use for multi-part endpoint will have issue

**Comment by 0xSage** [comment]
can you elaborate on this issue pls

**Comment by tikikun** [comment]
Problem:
- Currently the JSON_VALIDATOR macro only work for native json only endpoint and does not support multipart form data, this make the multipart form data not able to validate the request

Outcome:
- JSON_VALIDATOR macro for multi-part form data

**Comment by tikikun** [comment]
doing validation in this environment seems not ideal will be postponed or reconsidered later
