### ISSUE TITLE
nitro.exe has stopped working when load model by post request,within cpu mode on win server2012 r2.

### ISSUE THREAD

**Issue by theRotten0** [janhq/nitro#421]
nitro.exe has stopped working when load model by post request ":3928/inferences/llamacpp/loadmodel"  ,  with cpu mode in win server2012 r2.
(nitro version is  https://github.com/janhq/nitro/releases/download/v0.3.6/nitro-0.3.6-win-amd64.tar.gz  )
post data json is:

{
    "llama_model_path": "./model/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf",
    "ctx_len": 512,
}

![image](https://github.com/janhq/nitro/assets/45782285/cc3f2fd1-6017-4fe2-957a-e9a733b29041)

but,when i run in my laptop within cpu mode, everything is fine.   

What's this problem? How to solve this ? anybody helps ?

**Comment by tikikun** [comment]
I would advise to have more than 8GB of ram to attempt loading model into memory, 2GB is quite limiting
