### ISSUE TITLE
bug: model causing an unknown long wait for a response (and other issues)

### ISSUE THREAD

**Issue by Glashkoff** [janhq/nitro#430]
**Describe the bug**
In our Discord, people mention the low speed of the second response or an empty response. I came across a model that causes all these problems in 0.4.6:
1) Attempting to regenerate the response may hangs on the progress bar "Generating response" (thread and log of this issue in the attached zip archive)
2) During the conversation, the speed decreases with each new response
3) Sometimes instead of a response - an empty message
4) Sometimes the response repeats infinitely without stop

This model: [stable-code-3b.Q8_0.gguf](https://huggingface.co/brittlewis12/stable-code-3b-GGUF/blob/main/stable-code-3b.Q8_0.gguf)
model.json is default for 0.4.6
It is clear that there is some incompatibility with the default Jan settings here, but it would be nice to somehow handle this or inform the user that something is wrong. 
I hope this example will help diagnose and fix or somehow handle the described problems.

**Steps to reproduce**
Download my thread.json and try to generate a response with the model from the link above in this thread. The result is unpredictable, but in 9 out of 10 cases - it's an irrelevant answer to the query in the form of one or several paragraphs of text consisting of words or code.

**Expected behavior**
For this model, special prompt_template and probably retrieval_template are needed. Therefore, under the current conditions, an inadequate response is expected in terms of meaning. However, it should be at least some with stable speed and without freezing the progress bar for generating the answer.

**Environment details**
Operating System: Windows 11 Pro x64 23H2 (build 22631.3085)
Jan Version: 0.4.6
Processor: AMD Ryzen 5 5600
RAM: 64GB
Any additional relevant hardware specifics: RTX 3060 12GB, driver 551.23, rebar on, Cuda system fallback policy disabled

**Logs**
[jan_1707226938.zip](https://github.com/janhq/jan/files/14181251/jan_1707226938.zip)

**Comment by 0xSage** [comment]
It's weird that users are seeing more degradation when they go from `online to offline` though. Worth investigating.

**Comment by Brog33** [comment]
i am experiencing this same issue from time to time. tell me if you need some help testing.

**Comment by tikikun** [comment]
alread fixed
