### ISSUE TITLE
Bug: Nitro on linux unable to start

### ISSUE THREAD

**Issue by hiento09** [janhq/nitro#46]
Nitro requires certain dependencies to start, which is not convenient for users.

![image](https://github.com/janhq/nitro/assets/136591877/667227e4-6697-4285-ad91-5071adbc57ec)

**Comment by tikikun** [comment]
Tested on these below systems without issues
Ubuntu - 22.04 base - no CUDA - PASS
Ubuntu - 20.04 base - no CUDA - PASS
Debian stable - no CUDA - PASS
Ubuntu - 22.04 base - CUDA - PASS
Ubuntu - 20.04 base - CUDA - PASS
Debian stable - CUDA - PASS

It seems the original issue coming from outdated libc, which should be updated, will revisit later on and add automated test later, close for now.
