### ISSUE TITLE
epic: Nitro supports speech/hear capabilities

### ISSUE THREAD

**Issue by hiro-v** [janhq/nitro#59]
I would like to run TTS and STT supported in Nitro for my personal usage (self hosted Otter.ai)
For now nitro supports "think" - running LLM
This new feature is "hear"

https://platform.openai.com/docs/api-reference/audio/createTranscription

via whisper or something

**Comment by tikikun** [comment]
need to resolve the difference in ggml model + file between whisper and llama cpp

**Comment by 0xSage** [comment]
Impact: provides voice transcription

**Comment by dan-jan** [comment]
Untagging as an epic in favor of https://github.com/janhq/jan/issues/295
