### ISSUE TITLE
feat: Nitro speed up for 1st inference time after model loaded

### ISSUE THREAD

**Issue by vuonghoainam** [janhq/nitro#63]
**Problem**
The first request to nitro web server is slow, which make me frustrated. When it's ready, pls make sure me as a user can get quick result.

**Success Criteria**
- 1st request from user should be quick
- You should do mock request after loading model for the first time
- The /health should yield 500 indicating the model warm up process is not done yet, else 200 if done. The case for process exit has been handled

**Additional context**
None atm

**Comment by 0xSage** [comment]
I second this feature. From the app side, if a model is "started", we expect the models to respond lightening fast.
