### ISSUE TITLE
feat: Add support for inference parameters 

### ISSUE THREAD

**Issue by vuonghoainam** [janhq/nitro#77]
**Problem**
- I need to use Nitro as API for LLM
- Add support for using temperature, max_token, penalty in API call
- Add stream False
- Add stop

**Success Criteria**
- Fully supported

**Additional context**
- Check from LMStudio
<img width="317" alt="Screenshot_2023-10-16_at_6 52 14_PM" src="https://github.com/janhq/nitro/assets/22463238/ec7e8832-12e2-4fef-a116-0b2380cf9619">

**Comment by dan-jan** [comment]
@vuonghoainam - Btw, the screenshot is broken

**Comment by tikikun** [comment]
These below params will be added

frequency_penalty
logit_bias
stop
