### ISSUE TITLE
feat: Nitro LLM to support custom instructions

### ISSUE THREAD

**Issue by vuonghoainam** [janhq/nitro#89]
**Problem**
- Nitro to support custom instructions

**Success Criteria**
- Curl with example input/ output

**Additional context**
![Screenshot 2023-10-20 at 11 56 37 AM](https://github.com/janhq/nitro/assets/22463238/6b018365-1df4-44d0-a3a8-056d8ab389d3)

**Comment by tikikun** [comment]
done with the pre-prompt backlog
